language: android
jdk: oraclejdk8
android:
  components:
     - tools
     - platform-tools
     - tools
     - build-tools-25.0.2
     - android-19
     - android-25
     - extra-android-m2repository
     - sys-img-armeabi-v7a-android-19
     - sys-img-armeabi-v7a-android-25
  licenses:
    - 'android-sdk-license-.+'
before_script:
  - ./init.sh
  - echo no | android create avd --force -n test -t "android-21" --abi "armeabi-v7a"
  - emulator -avd test -no-audio -no-window &
  - ./android-wait-for-emulator.sh
  - adb shell input keyevent 82 &
script:
    - ./gradlew test
    - ./gradlew connectedAndroidTest